### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by richardalmonte** [dmurawsky/ionic2-odata#1]
Hi, 
this app helped me a lot, but I'm still having a problem, how can i use the basic authentication.
The service I'm consuming requires authentication and, all of my http response are 401.

Can you add an example of how to solve it?

thanks a lot!

**Comment by dmurawsky** [comment]
Hey Richard,

If you're looking for the most basic Authentication and expect it to be easy, you'll most likely be disappointed. If it's possible you can use something like https://firebase.google.com that takes a lot of the headache away. 

Hope that helps!
